# Generated by Django 5.1.3 on 2024-11-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('SupplierID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('ContactPerson', models.CharField(max_length=100)),
                ('ContactEmail', models.EmailField(blank=True, max_length=100, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('ActiveStatus', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=8)),
                ('ContractStartDate', models.DateField(blank=True, null=True)),
                ('ContractEndDate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
